---
# Per environment values which override defaults in hmpps-court-cases-release-dates-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: court-cases-release-dates-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    ADJUSTMENTS_API_URL: "https://adjustments-api-preprod.hmpps.service.justice.gov.uk"
    HMPPS_COURT_CASES_AND_RELEASE_DATES_UI_URL: "https://court-cases-release-dates-preprod.hmpps.service.justice.gov.uk"
    HMPPS_REMAND_AND_SENTENCING_UI_URL: "https://remand-and-sentencing-preprod.hmpps.service.justice.gov.uk"
    HMPPS_ADJUSTMENTS_UI_URL: "https://adjust-release-dates-preprod.hmpps.service.justice.gov.uk"
    HMPPS_RECALLS_UI_URL: "https://record-a-recall-preprod.hmpps.service.justice.gov.uk"
    HMPPS_CALCULATE_RELEASE_DATES_UI_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    THINGS_TO_DO_FEATURE_TOGGLE: "true"
    HMPPS_IDENTIFY_REMAND_UI_URL: "https://identify-remand-periods-preprod.hmpps.service.justice.gov.uk"
    HMPPS_IDENTIFY_REMAND_API_URL: "https://identify-remand-periods-api-preprod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
