package uk.gov.justice.digital.hmpps.courtcasesreleasedatesapi.model

enum class ThingToDoType(val severity: ThingToDoSeverity) {
  CALCULATION_REQUIRED(ThingToDoSeverity.REQUIRED_BEFORE_CALCULATION),
  ADA_INTERCEPT(ThingToDoSeverity.REQUIRED_BEFORE_CALCULATION),
  REVIEW_IDENTIFIED_REMAND(ThingToDoSeverity.REQUIRED_BEFORE_CALCULATION),
  PREVIOUS_PERIOD_OF_UAL_FOR_REVIEW(ThingToDoSeverity.REQUIRED_BEFORE_CALCULATION),
  HMCTS_API_DOCUMENT_RECEIVED(ThingToDoSeverity.NOTIFICATION),
}
